on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Publish on npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
  
  notify:
    needs: publish 
    runs-on: ubuntu-latest
    steps:
      - name: Notify me on Telegram
        run: curl -s --data-urlencode "chat_id=${{ secrets.CHAT_ID }}" --data-urlencode "text=Launched _npm publish_ action for *puppeteer-helper*" ${{ secrets.API_TELEGRAM_URL }} > /dev/null
