on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout project
        uses: actions/checkout@v1
        
      - name: Publish on npm
        id: publish-npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
        
      - name: Notify new version
        if: steps.publish-npm.outputs.type != 'none'
        run: curl -s -d "chat_id=${{ secrets.CHAT_ID }}" -d "text=📦 *puppeteer-helper*:%0A✔️ New version v${{ steps.publish-npm.outputs.version }}" ${{ secrets.API_TELEGRAM_URL }} > /dev/null
